### PR TITLE
Version 2.0

### PR DESCRIPTION
**Pull request by Supuhstar**
I've worked on bringing this plugin to evergreen browsers, and to make them more reliably functional. I hope these changes are solid enough to be considered for the official repo.

### CODE REVIEW

**Comment by christophery** [comment]
Thanks for the pull request but I noticed a couple of issues:
- The HTML tags in the demo.html are uppercase, they should be all lowercase for consistency.
- Tumblr is misspelled in the demo.html file.
- You misspelled my name in the css file.
- I'd prefer not to have any branding images included with this project, seems unnecessary.

**Comment by Supuhstar** [comment]
Ah, glad you've noted these. I've:
- Made the HTML tags and attributes lowercase
- Changed "Tumbl" to "Reblog" (this wasn't a typo, but I understand the confusion, which might be shared by others)
- Oh, sorry! It must've been late or something. Fixed!
- Understood, moved to a special "branded" branch.
- Noted that one of the merge conflicts involved you removing your Twitter username form the Tweet button, so I respected that and did so again.

**Comment by Supuhstar** [comment]
Hey, @christophery! I tweaked some more things and finally fixed the merge conflicts in case you want to merge this request.

**Comment by christophery** [comment]
Hi @Supuhstar, took a look at your PR, everything looks fine except for two things I noticed:
- The Linkedin button is misaligned (see attached). This issue can be fixed by tweaking to `.slide-social .ss-button` CSS class, I just changed the `left` property to `34%`.

screen shot 2016-06-07 at 4 21 49 pm
- The buttons don't seem to function on iOS devices (seems to work fine on Android), this is due to the fact that the buttons are activated using `:hover` and iOS doesn't have any support for that. 

I Originally fixed this issue by using Modernizr to detect if the user was using a touch device and hid the `.ss-slide` on touch devices (see line 121 in the CSS).

Since you have removed the modernizr dependency you'll need a new way to detect touch devices/mobile and remove the action of hovering to reveal the social buttons on mobile (since no hover on mobile).

Thoughts?

**Comment by Supuhstar** [comment]
- Good catch; I'll do that. But... that still doesn't fix it when the LinkedIn share count is 10+
- Ah, I forgot Safari does that. My usual fix is to change the HTML so the `.slide-social` element has `tab-index="-1"` and add `:focus` selectors alongside `:hover` ones. Do you think that might help? I don't have any iOS devices to test this on.

**Comment by christophery** [comment]
- An alternative could be using the Linkedin share button without a counter?
- Unfortunately in my testing I've found out that `:focus` selectors don't seem to work/trigger the buttons on iOS (I could be wrong though). Honestly the best/easiest alternative I found was to use <a href="https://modernizr.com/download?touchevents-setclasses&q=touch">Modernizr</a> to test for touchevents and hide the `.ss-slide` element on when the `.touchevents` class is added to `body`.

**Comment by Supuhstar** [comment]
- That sounds reasonable.
- Alright; I'll see if I can find an iOS device to do some tests. I really wanna try to get this working with zero JS.

**Comment by christophery** [comment]
That's understandable, it might be difficult to detect touch devices/mobile without using JS (unless there's a better workaround for mobile).

**Comment by christophery** [comment]
@Supuhstar I may have stumbled upon a solution for iOS...all I added was `cursor: pointer;` to `.slide-social`. On desktop it behaves normally and on iOS + Android it seems to work fine as-well.

The only downside I can see to this solution is that desktop it makes the entire button look click-able (ie a link) and the user might think that clicking anywhere (like the icon) on the button will trigger the share.

**Comment by Supuhstar** [comment]
That's promising! What if we just add `cursor:pointer` to `.ss-slide`, and change `.slide-social:hover .ss-slide` to `.slide-social:hover .ss-slide, .slide-social .ss-slide:hover`?

**Comment by christophery** [comment]
That sounds good to me! I'll merge these changes and apply the fixes that we've discussed.

**Comment by Supuhstar** [comment]
Awesome! Glad we could get this worked out.

**Pull request merged**
